typography_spectrum: 0.6197584508918226
color:
  brandStrength: 0.8101389675866812
  lightness: 0.9622699480969459
  saturation: 0.8610978969372809
  rhythmicContrast: 0.6089713075198233
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.454787211259827
name: Spicy Fingers
navigation:
  - name: (1) Spicy Fingers
    id: 3df0b1a9-0750-4896-a1fd-510c9b0bf06e
    type: content
  - name: (2) two Spicy Fingers
    id: 8e5fcb58-019c-4c4e-9066-965fee5c0545
    type: content
  - name: (3) three Spicy Fingers
    id: 4cc6ca53-7218-439d-aec7-a3fd7eeacdb7
    type: content
  - name: (4) four Spicy Fingers
    id: 5a3ab81c-f9c3-482f-a20c-705a4b283a11
    type: content
  - name: (5) five Spicy Fingers
    id: 070e75f6-b096-4b02-b6f1-239c565b5225
    type: content
  - name: (6) six Spicy Fingers
    id: 5937823c-b2ce-4dae-a69d-b6555a3edf59
    type: content
title: our Mexican adventure
description: life in the Yucatan
